version: "3"

services:
  smtp4dev:
    image: rnwood/smtp4dev:prerelease
    restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
      - '5000:80'
      # Change the number before : to the port the SMTP server should be accessible on
      - '25:25'




